### PR TITLE
Coding conventions

### PR DESCRIPTION
**Pull request by shubhamthakur463**
Hi there
PART B is also done. Below mentioned are the files assigned to each of the group members to modify them according to decided coding conventions.

Shubham Thakur - include/atomics/receiverCadmium.hpp
                                 src/data_structures/message.cpp
                                 test/src/sender/main.cpp

Gagandeep Singh - src/top_model/main.cpp
                                  include/data_structures/message.hpp
                                  test/src/receiver/main.cpp

Kindly Review them and close this pull request as soon as possible.
Thanks.

### CODE REVIEW

**Comment by gagandeep8030** [comment]
Hi Team,

We have submitted the pull request for Part B 4 days ago. Kindly review it.
Thanks.

**Comment by shubhamthakur463** [comment]
Requested changes were made. Kindly review the pull request.

**Comment by shubhamthakur463** [comment]
Suggested changes have been made inside receiverCadmium.hpp.
Kindly review it again.
Thanks.

**Comment by shubhamthakur463** [comment]
There is no "4 space" at line 32 in receiverCadmium.hpp
And I think there is no need for indentation there.

Thanks for pointing out the character limit mistake. Kindly let me know if there is any other thing that needs to be modified.

**Pull request merged**
